services:
  - type: web
    name: mad2moi-blog-admin
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: mad2moi_blog
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: ADMIN_SESSION_SECRET
        sync: false
    healthCheckPath: /
    autoDeploy: true
